apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-showroom-ingress
  namespace: car-showroom
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.uae-carshowroom.com
    - app.uae-carshowroom.com
    secretName: car-showroom-tls
  rules:
  - host: api.uae-carshowroom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
  - host: app.uae-carshowroom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
